<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><TreatWarningsAsErrors>true</TreatWarningsAsErrors></PropertyGroup>
  <ItemGroup><Compile Include="../../Prelude/Combat/*.cs" Link="Combat/%(Filename)%(Extension)" /><Compile Include="../../Prelude/DataModel/AbilityId.cs" Link="DataModel/AbilityId.cs" /><Compile Include="../../Prelude/DataModel/ItemId.cs" Link="DataModel/ItemId.cs" /><Compile Include="../../Prelude/DataModel/DamageType.cs" Link="DataModel/DamageType.cs" /><Compile Include="../../Prelude/DataModel/WeaponData.cs" Link="DataModel/WeaponData.cs" /><Compile Include="../../Prelude/DataModel/ItemData.cs" Link="DataModel/ItemData.cs" /><Compile Include="../../Prelude/DataModel/DamageCategory.cs" Link="DataModel/DamageCategory.cs" /><Compile Include="../../Prelude/DataModel/WeaponRange.cs" Link="DataModel/WeaponRange.cs" /></ItemGroup>
</Project>
