<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.9" />
    <PackageReference Include="Nexus.GameEngine" Version="1.0.0-dev" />
    <ProjectReference Include="..\Shared\Prelude.Shared\Prelude.Shared.csproj" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.windows.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Prelude</AssemblyName>
    <RootNamespace>NexusRealms.Prelude.Desktop</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <Compile Remove="Program.Linux.cs" />
    <Compile Remove="Program.MacOS.cs" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <Compile Remove="Program.Windows.cs" />
    <Compile Remove="Program.MacOS.cs" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <Compile Remove="Program.Windows.cs" />
    <Compile Remove="Program.Linux.cs" />
  </ItemGroup>

</Project>